# Generated by Django 5.2.5 on 2025-09-07 08:49

import datetime
import django.db.models.deletion
import questions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('part', models.CharField(choices=[('A', 'Part A - MCQ (Single Choice)'), ('B', 'Part B - MCQ (Multiple Choice)'), ('C', 'Part C - MCQ (Other format)'), ('D', 'Part D - Fill in the blanks'), ('E', 'Part E - Long answer (100-120 words)'), ('F', 'Part F - True/False')], default='A', max_length=1)),
                ('marks', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.trade')),
            ],
            options={
                'verbose_name': 'QP Delete',
                'verbose_name_plural': '3 QP Delete',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_paper', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], default='Primary', help_text='Select whether this is a Primary or Secondary paper', max_length=20)),
                ('is_common', models.BooleanField(default=False, editable=False)),
                ('exam_duration', models.DurationField(blank=True, default=datetime.timedelta(seconds=10800), help_text='Enter exam duration in format HH:MM:SS (e.g., 01:30:00 for 1h30m)', null=True)),
                ('questions', models.ManyToManyField(through='questions.PaperQuestion', to='questions.question')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.trade')),
            ],
            options={
                'verbose_name': 'QP Mapping',
                'verbose_name_plural': '2 QP Mappings',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='paperquestion',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questionpaper'),
        ),
        migrations.CreateModel(
            name='QuestionUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/questions/', validators=[questions.models.validate_dat_file])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('decryption_password', models.CharField(default='default123', max_length=255)),
                ('trade', models.ForeignKey(blank=True, help_text='If set, all imported questions will be tagged with this trade.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.trade')),
            ],
            options={
                'verbose_name': 'QP Upload',
                'verbose_name_plural': '1 QP Upload',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='qp_assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.questionupload'),
        ),
        migrations.AlterUniqueTogether(
            name='paperquestion',
            unique_together={('paper', 'question')},
        ),
    ]
