# Generated by Django 5.2.5 on 2025-09-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questionpaper_part_distribution_examsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='part',
            field=models.CharField(choices=[('A', 'Part A - MCQ (Single Choice)'), ('B', 'Part B - MCQ (Multiple Choice)'), ('C', 'Part C - Short answer (20-30 words)'), ('D', 'Part D - Fill in the blanks'), ('E', 'Part E - Long answer (100-120 words)'), ('F', 'Part F - True/False')], default='A', max_length=1),
        ),
    ]
