# Generated by Django 5.2.5 on 2025-09-09 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.question'),
        ),
    ]
