# Generated by Django 4.2.11 on 2025-12-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_questionpaper_is_active_alter_paperquestion_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='question_paper',
            field=models.CharField(choices=[('Primary', 'Primary')], default='Primary', help_text='Select whether this is a Primary paper', max_length=20),
        ),
    ]
