# Generated by Django 5.2.5 on 2025-09-07 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('army_no', models.CharField(max_length=50, unique=True)),
                ('rank', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('brigade', models.CharField(blank=True, max_length=100, null=True)),
                ('corps', models.CharField(blank=True, max_length=100, null=True)),
                ('command', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=150)),
                ('dob', models.CharField(max_length=10, verbose_name='Date of Birth')),
                ('doe', models.DateField(verbose_name='Date of Enrolment')),
                ('aadhar_number', models.CharField(blank=True, max_length=12)),
                ('father_name', models.CharField(max_length=150)),
                ('photograph', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('nsqf_level', models.CharField(blank=True, max_length=50)),
                ('exam_center', models.CharField(blank=True, max_length=150, null=True)),
                ('training_center', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('primary_qualification', models.CharField(blank=True, max_length=150, null=True)),
                ('primary_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_credits', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_qualification', models.CharField(blank=True, max_length=150, null=True)),
                ('secondary_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_credits', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_viva_marks', models.IntegerField(blank=True, null=True)),
                ('primary_practical_marks', models.IntegerField(blank=True, null=True)),
                ('secondary_viva_marks', models.IntegerField(blank=True, null=True)),
                ('secondary_practical_marks', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exams.shift')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.trade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
