# Generated by Django 5.2.8 on 2025-12-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='aadhar_number',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='brigade',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='corps',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='photograph',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='cat',
            field=models.CharField(choices=[('JCOs (All tdes less Dvr MT,DR,EFS,Lmn and Tdn)', 'JCOs (All tdes less Dvr MT,DR,EFS,Lmn and Tdn)'), ('OR (All tdes less Dvr MT,DR,EFS,Lmn and Tdn)', 'OR (All tdes less Dvr MT,DR,EFS,Lmn and Tdn)'), ('JCOs/OR (Dvr MT,DR,EFS,Lmn and Tdn)', 'JCOs/OR (Dvr MT,DR,EFS,Lmn and Tdn)')], default='OR (All tdes less Dvr MT,DR,EFS,Lmn and Tdn)', max_length=255),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='med_cat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='trade_type',
            field=models.CharField(choices=[('Tech', 'Tech'), ('GD', 'GD')], default='Tech', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='rank',
            field=models.CharField(choices=[('Sigmn', 'Sigmn'), ('LNk', 'LNk'), ('Nk', 'Nk'), ('Hav', 'Hav'), ('CHM', 'CHM'), ('CQMH', 'CQMH'), ('RHM', 'RHM'), ('Nb Sub', 'Nb Sub'), ('Sub', 'Sub'), ('Sub Maj', 'Sub Maj')], max_length=50),
        ),
    ]
