# Generated by Django 4.2.11 on 2025-12-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_secondary_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='secondary_credits',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='secondary_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='secondary_practical_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='secondary_qualification',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='secondary_viva_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
