# Generated by Django 5.2.5 on 2025-12-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_candidateprofile_secondary_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='command',
            field=models.CharField(blank=True, choices=[('SC', 'Southern Command'), ('EC', 'Eastern Command'), ('WC', 'Western Command'), ('CC', 'Central Command'), ('NC', 'Northern Command'), ('SWC', 'South Western Command'), ('ANC', 'Andaman & Nicobar Command'), ('ARTRAC', 'ARTRAC')], max_length=20, null=True),
        ),
    ]
