# Generated by Django 5.2.5 on 2025-12-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_candidateprofile_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='rank',
            field=models.CharField(choices=[('Sigmn', 'Sigmn'), ('LNk', 'LNk'), ('Nk', 'Nk'), ('Hav', 'Hav'), ('CHM', 'CHM'), ('CQMH', 'CQMH'), ('RHM', 'RHM'), ('Nb Sub', 'Nb Sub'), ('Sub', 'Sub'), ('Sub Maj', 'Sub Maj'), ('L|Hav', 'L|Hav'), ('AV', 'AV'), ('Loc Hav', 'Loc Hav'), ('Loc Nk', 'Loc Nk')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='trade_type',
            field=models.CharField(choices=[('Tech', 'Tech'), ('GD', 'Non-Tech')], default='Tech', max_length=50),
        ),
    ]
