# Generated by Django 5.2.5 on 2025-12-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_candidateprofile_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='trade_type',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Non-Tech', 'Non-Tech')], default='Tech', max_length=50),
        ),
    ]
