# Generated by Django 5.2.5 on 2025-12-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_candidateprofile_trade_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
