# Generated by Django 5.2.5 on 2025-09-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comd', models.CharField(blank=True, choices=[('SC', 'Southern Command'), ('EC', 'Eastern Command'), ('WC', 'Western Command'), ('CC', 'Central Command'), ('NC', 'Northern Command'), ('SWC', 'South Western Command'), ('ANC', 'Andaman & Nicobar Command'), ('ARTRAC', 'ARTRAC')], max_length=20)),
                ('exam_Center', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Exam center',
                'verbose_name_plural': 'Exam centers',
            },
        ),
    ]
